import React, { useId, useState } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { CheckMarkIcon } from '@ui/components/icons';
import style from './Toggle.module.scss';

export function Toggle({
  tabIndex,
  label,
  active,
  onChange,
  disabled,
  className,
  id,
  icon,
}) {
  const autoGeneratedId = useId();
  const [uiid] = useState(id || autoGeneratedId);

  const resolvedClassName = classNames(style.toggle, className, {
    [style.isActive]: active,
    [style.isDisabled]: disabled,
  });

  const handleChange = () => {
    onChange(!active);
  };

  return (
    <label htmlFor={uiid} className={resolvedClassName} tabIndex={tabIndex}>
      <input
        id={uiid}
        type="checkbox"
        onChange={handleChange}
        checked={active}
        disabled={disabled}
      />
      <span className={style.track}>
        <span className={style.switch}>
          {icon && <span className={style.icon}>{icon}</span>}
        </span>
      </span>
      {label && <span className={style.label}>{label}</span>}
    </label>
  );
}

Toggle.propTypes = {
  tabIndex: PropTypes.number,
  label: PropTypes.string,
  active: PropTypes.bool,
  onChange: PropTypes.func,
  disabled: PropTypes.bool,
  className: PropTypes.string,
  id: PropTypes.string,
  icon: PropTypes.element,
};

Toggle.defaultProps = {
  tabIndex: null,
  label: '',
  active: false,
  onChange: () => {},
  disabled: false,
  className: '',
  id: undefined,
  icon: <CheckMarkIcon />,
};
